### ISSUE TITLE
@octopusdeploy/api-client without Repository object

### ISSUE THREAD

**Issue by gustavopalminha** [OctopusDeploy/api-client.ts#137]
When runing the script obtained from here https://octopus.com/docs/octopus-rest-api/examples/deployments/create-and-deploy-a-release

the Repository object ia not available at '@octopusdeploy/api-client' so I cant import it,

**Comment by jbristowe** [comment]
Hey @gustavopalminha! :wave: Good catch! Our documentation is out-of-date and needs to be updated to reflect the recent changes we've made to the API client.

**Comment by evgeniyefimov** [comment]
@jbristowe could you please provide some docs how to release and deploy with new API? New API is very different then it was before.

**Comment by ann-mwangi** [comment]
Hi @evgeniyefimov, not sure what documentation you are looking for so I will send you our latest blogs that have links to the documentation.

- New Executions API: https://octopus.com/blog/faster-deployments-with-the-executions-api
- GitHub Actions V3: https://octopus.com/blog/github-actions-for-octopus-deploy-v3

In addition: for all the updated GitHub actions, we have a migration guide [like this one](https://github.com/OctopusDeploy/create-release-action/blob/main/migration-guide.md#migration-guide).

Hope that helps.
